<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6LxV29v\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6LxV29v/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6LxV29v.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6LxV29v\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6LxV29v\App_KernelDevDebugContainer([
    'container.build_hash' => '6LxV29v',
    'container.build_id' => 'b8d2f58b',
    'container.build_time' => 1609944405,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6LxV29v');
